# Multiple Linear Regression with sklearn on real estate data

Given a real estate dataset. 

 file: 'real_estate_price_size_year1.csv'. 

Creating a multiple linear regression and with the following: 

-  the intercept and coefficient(s)
-  the R-squared and Adjusted R-squared
-  Comparing the R-squared and the Adjusted R-squared
-  Using the model to make a prediction about an apartment with size 750 sq.ft. from 2009
-  Find the univariate (or multivariate if you wish - see the article) p-values of the two variables.
-  Create a summary table with your findings

In this exercise, the dependent variable is 'price', while the independent variables are 'size' and 'year'.

## Importing the relevant libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression


## Load the data

In [2]:
data = pd.read_csv( 'real_estate_price_size_year1.csv')
data

price     size  year
0   234314.144   643.09  2015
1   228581.528   656.22  2009
2   281626.336   487.29  2018
3   401255.608  1504.75  2015
4   458674.256  1275.46  2009
5   245050.280   575.19  2006
6   265129.064   570.89  2015
7   175716.480   620.82  2006
8   331101.344   682.26  2018
9   218630.608   694.52  2009
10  279555.096  1060.36  2009
11  494778.992  1842.51  2009
12  215472.104   694.52  2015
13  418753.008  1009.25  2018
14  444192.008  1300.96  2006
15  440201.616  1379.72  2006
16  248337.600   690.54  2018
17  234178.160   623.94  2006
18  225451.984   681.07  2006
19  299416.976  1027.76  2018
20  268125.080   620.71  2015
21  171795.240   549.69  2015
22  412569.472  1207.45  2015
23  183459.488   518.38  2015
24  168047.264   525.81  2009
25  362519.720  1103.30  2018
26  271793.312   570.89  2018
27  406852.304  1334.10  2015
28  297760.440   681.07  2015
29  368988.432  1496.36  2015
..         ...      ...   ...
70  276875.632  1021.95  2009
71  181587.576   643.41  2006
72  298926.496   656.22  2015
73  211724.096   549.80  2015
74  228313.024   685.48  2018
75  286161.600   685.48  2018
76  382120.152  1183.46  2018
77  365863.936  1334.10  2006
78  251560.040   682.26  2009
79  342988.456  1188.62  2006
80  180307.216   681.07  2006
81  408637.816  1122.34  2015
82  190909.056   681.07  2006
83  282683.544   643.09  2018
84  303597.216   685.48  2018
85  376253.808  1009.25  2018
86  154282.128   479.75  2006
87  327252.112  1028.41  2009
88  211904.536   601.66  2018
89  354512.112  1236.93  2018
90  251140.656   694.52  2018
91  338078.168  1071.55  2015
92  298170.880   694.52  2015
93  266684.248   698.29  2018
94  262477.856   698.29  2006
95  252460.400   549.80  2009
96  310522.592  1037.44  2009
97  383635.568  1504.75  2006
98  225145.248   648.29  2015
99  274922.856   705.29  2006

[100 rows x 3 columns]

In [3]:
data.describe()

price         size         year
count     100.000000   100.000000   100.000000
mean   292289.470160   853.024200  2012.600000
std     77051.727525   297.941951     4.729021
min    154282.128000   479.750000  2006.000000
25%    234280.148000   643.330000  2009.000000
50%    280590.716000   696.405000  2015.000000
75%    335723.696000  1029.322500  2018.000000
max    500681.128000  1842.510000  2018.000000

In [4]:
data.head()

price     size  year
0  234314.144   643.09  2015
1  228581.528   656.22  2009
2  281626.336   487.29  2018
3  401255.608  1504.75  2015
4  458674.256  1275.46  2009

## Creating the regression

### Declaring the dependent and the independent variables

In [5]:
x = data[["size","year"]]
y = data["price"]

### Regression

In [6]:
reg = LinearRegression()

In [7]:
reg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

### Finding the intercept

In [8]:
reg.intercept_

-5772267.017463278

### Finding the coefficients

In [9]:
reg.coef_

array([ 227.70085401, 2916.78532684])

### Calculate the R-squared

In [10]:
reg.score(x,y)

0.7764803683276793

### Calculate the Adjusted R-squared

In [11]:
# R2 = 1-(1-r2)*n-1/n-p-1
r2 = reg.score(x,y)
n = x.shape[0]
p = x.shape[1]
Adjusted_r2 = 1-(1-r2)*n-1/(n-p-1)
Adjusted_r2

-21.362272445582587

### Compare the R-squared and the Adjusted R-squared

Answer...

### Compare the Adjusted R-squared with the R-squared of the simple linear regression

Answer...

### Making predictions

Find the predicted price of an apartment that has a size of 750 sq.ft. from 2009.

In [12]:
reg.predict([[750,2009]])

array([258330.34465995])

# Calculate the univariate p-values of the variables

In [13]:
from sklearn.feature_selection import f_regression

In [14]:
f_regression(x,y)

(array([285.92105192,   0.85525799]), array([8.12763222e-31, 3.57340758e-01]))

In [15]:
p_value = f_regression(x,y)[1]
p_value

array([8.12763222e-31, 3.57340758e-01])

In [16]:
p_value.round(3)

array([0.   , 0.357])

### Create a summary table with your findings

In [17]:
new_table = pd.DataFrame(data=x.columns.values, columns = ["features"])
new_table["coefficient"]  = reg.coef_
new_table["p_value"] = p_value.round(3)
new_table

features  coefficient  p_value
0     size   227.700854    0.000
1     year  2916.785327    0.357

Answer...